spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driverClassName: 'org.postgresql.Driver'
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
financial-tool:
  jwt-properties:
    token-duration-seconds: 6000
  cookie-properties:
    token-cookie-duration-seconds: 6000
