spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    driverClassName: 'org.postgresql.Driver'
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        jdbc:
          time_zone: UTC
  flyway:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
    postgressql:
      transactional-lock: false



financial-tool:
  jwt-properties:
    token-duration-seconds: 600

