spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}'
    username: '${DATABASE_USERNAME:postgres}'
    password: '${DATABASE_PASSWORD:postgres}'
    driverClassName: 'org.postgresql.Driver'
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        jdbc:
          time_zone: UTC
  flyway:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}'
    username: '${FLYWAY_USERNAME:postgres}'
    password: '${FLYWAY_PASSWORD:postgres}'
    postgressql:
      transactional-lock: false

logging:
  level:
    root: INFO


financial-tool:
  white-lists:
    user-allowed-emails:
      enable: true
      emails-list: '${ALLOWED_EMAIL_LIST:thon_ataide10@hotmail.com}'
  jwt-properties:
    token-duration-seconds: 12000

