CREATE UNIQUE INDEX CONCURRENTLY USER_USERNAME_INDEX
    ON USER_CREDENTIALS_DATA (USER_USERNAME);

CREATE UNIQUE INDEX CONCURRENTLY USER_ACCOUNT_ID_INDEX
    ON USER_CREDENTIALS_DATA (USER_ACCOUNT_ID);
