ALTER TABLE USER_CREDENTIALS_DATA
    ADD CONSTRAINT UNIQUE_USERNAME UNIQUE USING INDEX USER_USERNAME_INDEX;

ALTER TABLE USER_CREDENTIALS_DATA
    ADD CONSTRAINT NOT_NULL_ACCOUNT_ID UNIQUE USING INDEX USER_ACCOUNT_ID_INDEX;
