INSERT INTO EXPENSE_CATEGORY (NAME) VALUES ('Luz'),
    ('Água'),
    ('Aluguel'),
    ('Condomínio'),
    ('Farmácia'),
    ('Mercado'),
    ('TV/Telefone/Internet'),
    ('Manutenção Residêncial'),
    ('Manutenção Automóvel'),
    ('Combustível'),
    ('Seguros'),
    ('Viagem'),
    ('Lazer'),
    ('Restaurante/Lanche/Pizza');
