CREATE TABLE EXPENSE
(
    ID                  BIGINT GENERATED ALWAYS AS IDENTITY,
    EXPENSE_DESCRIPTION VARCHAR(50)           NOT NULL,
    AMOUNT              DECIMAL(19, 2)        NOT NULL,
    CATEGORY_ID         BIGINT                NOT NULL,
    EXPENSE_OWNER       UUID                  NOT NULL,
    IS_FIXED_EXPENSE    BOOLEAN DEFAULT FALSE NOT NULL,
    DAT_PURCHASE        DATE,
    DAT_CREATION        TIMESTAMP(6)          NOT NULL,
    DAT_UPDATE          TIMESTAMP(6)          NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES EXPENSE_CATEGORY (ID)
);
