CREATE INDEX CONCURRENTLY CATEGORY_INDEX
    ON EXPENSE (CATEGORY_ID);

CREATE INDEX CONCURRENTLY EXPENSE_OWNER_INDEX
    ON EXPENSE (EXPENSE_OWNER);

CREATE INDEX CONCURRENTLY DAT_PURCHASE_INDEX
    ON EXPENSE (DAT_PURCHASE);

CREATE INDEX CONCURRENTLY IS_FIXED_INDEX
    ON EXPENSE (IS_FIXED_EXPENSE);