INSERT INTO EXPENSE_CATEGORY (NAME) VALUES
    ('Água'),
    ('Luz'),
    ('Aluguel'),
    ('Condomínio'),
    ('TV/Telefone/Internet'),
    ('Manutenção Residêncial'),
    ('Seguro Residêncial'),
	('Cursos'),
	('Livros'),
	('Palestras/Seminários'),
	('Escola'),
	('Material escolar'),
	('Padaria'),
	('Mercado'),
	('Açougue'),
	('Restaurante'),
	('Lanche/Pizza/Outros'),
	('Empréstimo'),
	('Fatura do Cartão de Crédito'),
	('Consórcio'),
	('Serviços bancários'),
    ('Farmácia'),
    ('Consultas/Procedimentos'),
    ('Equipamentos De Saúde'),
	('Atividade Física'),
	('Passagem/Ticket/Transporte Escolar'),
	('Combustível'),
	('Aplicativos'),
	('Manutenção Automotiva'),
	('Pedágio'),
	('Multas'),
	('Taxas/Impostos Residênciais'),
	('Taxas/Impostos Automotivos'),
	('Taxas/Documentação'),
	('Imposto de Renda'),
	('Taxas jurídicas e de Advocacia'),
	('Viagem'),
    ('Cinema/Teatro'),
    ('Show/Evento'),
    ('Serviçõs de Streams'),
    ('Restaurante/Lanche/Pizza'),
    ('Presentes'),
    ('Gastos Pessoais');